---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# ahhray

...

## Installation

You can install the released version of ahhray from [CRAN](https://CRAN.R-project.org) with:

``` r
install.packages("ahhray")
```

And the development version from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("club-cooking/ahhray")
```
## Use

```{r example}
library(ahhray)
```

### Events

Get information about a particular event:

```{r}
ra_get_event(event_id = 1422257)
```

Get listed event regions:

```{r}
regions <- ra_get_regions()

head(regions)
```

Get events that took place in a region, within a particular month:

```{r}
morocco_events <- ra_get_region_events(region_code = "morocco", start_date = "2020-01-01")

head(morocco_events)
```

Get all events that took place in a specific club:

```{r}
corsica_events <- ra_get_club_events(club_id = 2587)

head(corsica_events$`2020`)
```
